### ISSUE TITLE
Exception when serializing type: obj option

### ISSUE THREAD

**Issue by yuqiu42** [jet/Vertigo.Json#6]
Sample code
```
        let l = ["a", (Some (1 :> obj))]
        printfn "json: %s" (l |> Map.ofList |> Json.serialize)
```
Exception:
```
Unhandled Exception: System.Exception: Unknown type: Type=Object
   at Vertigo.Json.Internals.NonOption$cont@204(JsonConfig config, Object value, Type t, Unit unitVar)
   at Vertigo.Json.Internals.Serialize.NonOption(JsonConfig config, Type t, Object value, JsonProperty attr)
   at Vertigo.Json.Internals.Serialize.Option(JsonConfig config, Type t, Object o, JsonProperty attr)
   at Vertigo.Json.Internals.Map@263.Invoke(Object o)
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@74.DoMoveNext(b& curr)
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
   at Vertigo.Json.Internals.Serialize.Map(JsonConfig config, IEnumerable kvps)
   at Vertigo.Json.Json.serialize(Object objekt)
```

**Comment by Tombert** [comment]
This is not a very high priority bug, but it's a bug nonetheless, will look at this this evening.

**Comment by Tombert** [comment]
For anyone stuck on this, a workaround is to cast the entire Option as an `obj` instead of the internal value: 

```
        let l = ["a", (Some (1) :> obj)]
        printfn "json: %s" (l |> Map.ofList |> Json.serialize)
```
Hopefully this fixes anyone's problems until I can push a patch.
